name: Ralph-LSP-CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '**'

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 17
      - run: sbt "compile;test"

#  test-windows:
#    runs-on: windows-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: 17
#      - run: sbt "compile;test"
